# Importar Pandas

In [1]:
#importa pandas
import pandas as pd

# Crear una Serie

In [ ]:
# Crea una Serie de los numeros 10, 20 and 30.
numeros = pd.Series([10, 20, 30])
numeros

In [ ]:
# Crea una Serie con tres objetos: 'rojo', 'verde', 'azul'
colores = ['rojo', 'verde', 'azul']
df = pd.DataFrame({'numeros': [10, 20, 30], 'colores': ['rojo', 'verde', 'azul']})

# Crear un Dataframe

In [ ]:
# Crea un dataframe vacío llamado 'df'

In [ ]:
# Crea una nueva columna en el dataframe, y asignale la primera serie que has creado
df = pd.DataFrame('numeros': [10, 20, 30])

In [ ]:
# Crea otra columna en el dataframe y asignale la segunda Serie que has creado
df = pd.DataFrame('colores': ['rojo', 'verde', 'azul'])

# Leer un dataframe

In [ ]:
# Lee el archivo llamado 'avengers.csv" localizado en la carpeta "data" y crea un DataFrame, llamado 'avengers'. 
# El archivo está localizado en "data/avengers.csv"

In [29]:
import pandas as pd
avengers = pd.read_csv("./data/pandas/avengers.csv")

In [30]:
avengers.head()

,URL,nombre,n_apariciones,actual,genero,fecha_inicio,Notes
0,http://marvel.wikia.com/Henry_Pym_(Earth-616),"Henry Jonathan ""Hank"" Pym",1269,YES,MALE,1963,Merged with Ultron in Rage of Ultron Vol. 1. A...
1,http://marvel.wikia.com/Janet_van_Dyne_(Earth-...,Janet van Dyne,1165,YES,FEMALE,1963,Dies in Secret Invasion V1:I8. Actually was se...
2,http://marvel.wikia.com/Anthony_Stark_(Earth-616),"Anthony Edward ""Tony"" Stark",3068,YES,MALE,1963,"Death: ""Later while under the influence of Imm..."
3,http://marvel.wikia.com/Robert_Bruce_Banner_(E...,Robert Bruce Banner,2089,YES,MALE,1963,"Dies in Ghosts of the Future arc. However ""he ..."
4,http://marvel.wikia.com/Thor_Odinson_(Earth-616),Thor Odinson,2402,YES,MALE,1963,Dies in Fear Itself brought back because that'...

#### BORRADOR

In [ ]:
# Lee el archivo llamado 'avengers.csv" localizado en la carpeta "data" y crea un DataFrame, llamado 'avengers'. 
# El archivo está localizado en "data/avengers.csv"

import pandas as pd

avengers = {'nombre':['Jonathan Pym','Janet van Dyne','Tony Stark',' Bruce Banner','Thor Odinson','Milhouse Jones'],
            'n_apariciones':[1269,1165,3068,2089,2402,612],
            'actual':['YES','YES','YES','YES','YES','YES'], 
            'genero':['masculino','femenino','masculino','masculino','masculino'], 
            'fecha_inicio':[1963,1963,1963,1963,1963,1963], 
            'notes':['Merged with Ultron in Rage of Ultron Vol. 1. A funeral was held.','Dies in Secret Invasion V1:I8. Actually was sent tto Microverse later recovered','Death: "Later while under the influence of Immortus Stark committed a number of horrible acts and was killed.','Dies in Ghosts of the Future arc. However "he had actually used a hidden Pantheon base to survive"','Dies in Fear Itself brought back because that is kind of the whole point. Second death in Time Runs Out has not yet returned','nada']}
actores = pd.DataFrame(avengers)
print(actores)

# Inspeccionar un dataframe

In [31]:
# Muestra las primeras 5 filas del DataFrame.

avengers.head(5)

,URL,nombre,n_apariciones,actual,genero,fecha_inicio,Notes
0,http://marvel.wikia.com/Henry_Pym_(Earth-616),"Henry Jonathan ""Hank"" Pym",1269,YES,MALE,1963,Merged with Ultron in Rage of Ultron Vol. 1. A...
1,http://marvel.wikia.com/Janet_van_Dyne_(Earth-...,Janet van Dyne,1165,YES,FEMALE,1963,Dies in Secret Invasion V1:I8. Actually was se...
2,http://marvel.wikia.com/Anthony_Stark_(Earth-616),"Anthony Edward ""Tony"" Stark",3068,YES,MALE,1963,"Death: ""Later while under the influence of Imm..."
3,http://marvel.wikia.com/Robert_Bruce_Banner_(E...,Robert Bruce Banner,2089,YES,MALE,1963,"Dies in Ghosts of the Future arc. However ""he ..."
4,http://marvel.wikia.com/Thor_Odinson_(Earth-616),Thor Odinson,2402,YES,MALE,1963,Dies in Fear Itself brought back because that'...

In [32]:
# Muestra las primeras 10 filas del DataFrame. 
avengers.head(10)

,URL,nombre,n_apariciones,actual,genero,fecha_inicio,Notes
0,http://marvel.wikia.com/Henry_Pym_(Earth-616),"Henry Jonathan ""Hank"" Pym",1269,YES,MALE,1963,Merged with Ultron in Rage of Ultron Vol. 1. A...
1,http://marvel.wikia.com/Janet_van_Dyne_(Earth-...,Janet van Dyne,1165,YES,FEMALE,1963,Dies in Secret Invasion V1:I8. Actually was se...
2,http://marvel.wikia.com/Anthony_Stark_(Earth-616),"Anthony Edward ""Tony"" Stark",3068,YES,MALE,1963,"Death: ""Later while under the influence of Imm..."
3,http://marvel.wikia.com/Robert_Bruce_Banner_(E...,Robert Bruce Banner,2089,YES,MALE,1963,"Dies in Ghosts of the Future arc. However ""he ..."
4,http://marvel.wikia.com/Thor_Odinson_(Earth-616),Thor Odinson,2402,YES,MALE,1963,Dies in Fear Itself brought back because that'...
5,http://marvel.wikia.com/Richard_Jones_(Earth-616),Richard Milhouse Jones,612,YES,MALE,1963,NaN
6,http://marvel.wikia.com/Steven_Rogers_(Earth-616),Steven Rogers,3458,YES,MALE,1964,Dies at the end of Civil War. Later comes back.
7,http://marvel.wikia.com/Clint_Barton_(Earth-616),Clinton Francis Barton,1456,YES,MALE,1965,Dies in exploding Kree ship in Averngers Vol. ...
8,http://marvel.wikia.com/Pietro_Maximoff_(Earth...,Pietro Maximoff,769,YES,MALE,1965,Dies in House of M Vol 1 Issue 7. Later comes ...
9,http://marvel.wikia.com/Wanda_Maximoff_(Earth-...,Wanda Maximoff,1214,YES,FEMALE,1965,Dies in Uncanny_Avengers_Vol_1_14. Later comes...

In [33]:
avengers.head(5)

,URL,nombre,n_apariciones,actual,genero,fecha_inicio,Notes
0,http://marvel.wikia.com/Henry_Pym_(Earth-616),"Henry Jonathan ""Hank"" Pym",1269,YES,MALE,1963,Merged with Ultron in Rage of Ultron Vol. 1. A...
1,http://marvel.wikia.com/Janet_van_Dyne_(Earth-...,Janet van Dyne,1165,YES,FEMALE,1963,Dies in Secret Invasion V1:I8. Actually was se...
2,http://marvel.wikia.com/Anthony_Stark_(Earth-616),"Anthony Edward ""Tony"" Stark",3068,YES,MALE,1963,"Death: ""Later while under the influence of Imm..."
3,http://marvel.wikia.com/Robert_Bruce_Banner_(E...,Robert Bruce Banner,2089,YES,MALE,1963,"Dies in Ghosts of the Future arc. However ""he ..."
4,http://marvel.wikia.com/Thor_Odinson_(Earth-616),Thor Odinson,2402,YES,MALE,1963,Dies in Fear Itself brought back because that'...

In [34]:
# tail -> retorna los últimos 5 resultados del df
avengers.tail()

,URL,nombre,n_apariciones,actual,genero,fecha_inicio,Notes
168,http://marvel.wikia.com/Eric_Brooks_(Earth-616)#,Eric Brooks,198,YES,MALE,2013,NaN
169,http://marvel.wikia.com/Adam_Brashear_(Earth-6...,Adam Brashear,29,YES,MALE,2014,NaN
170,http://marvel.wikia.com/Victor_Alvarez_(Earth-...,Victor Alvarez,45,YES,MALE,2014,NaN
171,http://marvel.wikia.com/Ava_Ayala_(Earth-616)#,Ava Ayala,49,YES,FEMALE,2014,NaN
172,http://marvel.wikia.com/Kaluu_(Earth-616)#,Kaluu,35,YES,MALE,2015,NaN

# Tamaño del DataFrame

In [35]:
# Muestra el tamaño del DataFrame
avengers.describe()

       n_apariciones  fecha_inicio
count     173.000000    173.000000
mean      414.052023   1988.445087
std       677.991950     30.374669
min         2.000000   1900.000000
25%        58.000000   1979.000000
50%       132.000000   1996.000000
75%       491.000000   2010.000000
max      4333.000000   2015.000000

# Data types en un DataFrame

In [36]:
# Muestra los data types del dataframe
avengers.dtypes

URL              object
nombre           object
n_apariciones     int64
actual           object
genero           object
fecha_inicio      int64
Notes            object
dtype: object

# Editar el indice (index)

In [37]:
# Cambia el indice a la columna "fecha_inicio".

avengers1 = avengers.set_index("fecha_inicio")

In [38]:
avengers1.head()

,URL,nombre,n_apariciones,actual,genero,Notes
fecha_inicio,,,,,,
1963,http://marvel.wikia.com/Henry_Pym_(Earth-616),"Henry Jonathan ""Hank"" Pym",1269,YES,MALE,Merged with Ultron in Rage of Ultron Vol. 1. A...
1963,http://marvel.wikia.com/Janet_van_Dyne_(Earth-...,Janet van Dyne,1165,YES,FEMALE,Dies in Secret Invasion V1:I8. Actually was se...
1963,http://marvel.wikia.com/Anthony_Stark_(Earth-616),"Anthony Edward ""Tony"" Stark",3068,YES,MALE,"Death: ""Later while under the influence of Imm..."
1963,http://marvel.wikia.com/Robert_Bruce_Banner_(E...,Robert Bruce Banner,2089,YES,MALE,"Dies in Ghosts of the Future arc. However ""he ..."
1963,http://marvel.wikia.com/Thor_Odinson_(Earth-616),Thor Odinson,2402,YES,MALE,Dies in Fear Itself brought back because that'...

# Ordenar el indice

In [55]:
# Ordena el índice de forma descendiente


avengers.sort_values("n_apariciones",ascending=False)

,URL,nombre,n_apariciones,actual,genero,fecha_inicio,Notes
73,http://marvel.wikia.com/Peter_Parker_(Earth-616)#,Peter Benjamin Parker,4333,YES,MALE,1990,Since joining the New Avengers: First death Ki...
6,http://marvel.wikia.com/Steven_Rogers_(Earth-616),Steven Rogers,3458,YES,MALE,1964,Dies at the end of Civil War. Later comes back.
92,http://marvel.wikia.com/James_Howlett_(Earth-6...,"James ""Logan"" Howlett",3130,YES,MALE,2005,Died in Death_of_Wolverine_Vol_1_4. Has not ye...
2,http://marvel.wikia.com/Anthony_Stark_(Earth-616),"Anthony Edward ""Tony"" Stark",3068,YES,MALE,1963,"Death: ""Later while under the influence of Imm..."
4,http://marvel.wikia.com/Thor_Odinson_(Earth-616),Thor Odinson,2402,YES,MALE,1963,Dies in Fear Itself brought back because that'...
...,...,...,...,...,...,...,...
117,http://marvel.wikia.com/Dennis_Sykes_(Earth-616)#,Dennis Sykes,6,NO,MALE,2010,Died in Heroic_Age:_One_Month_to_Live_Vol_1_5 ...
65,http://marvel.wikia.com/Gene_Lorrene_(Earth-616)#,Gene Lorrene,4,NO,MALE,2005,NaN
68,http://marvel.wikia.com/Doug_Taggert_(Earth-616)#,Doug Taggert,3,NO,MALE,2005,Accidently killed by Zaran
39,http://marvel.wikia.com/Moira_Brandon_(Earth-6...,Moira Brandon,2,NO,FEMALE,1993,Died in her second appearance earns honorary A...
125,http://marvel.wikia.com/Fiona_(Inhuman)_(Earth...,Fiona,2,YES,FEMALE,1900,NaN

# Resetear el indice

In [61]:
# Resetea el índice
avengers = avengers.reset_index()
del avengers['index']

In [62]:
avengers = avengers.reindex()